routes/web.php
<?php

use GuzzleHttp\Middleware;
use Brian2694\Toastr\Toastr;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Artisan;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ClientController;
use App\Http\Controllers\Admin\ContactUsController;
use App\Http\Controllers\Admin\ContentController;
use App\Http\Controllers\Admin\MessageController;
use App\Http\Controllers\Admin\PhotoGalleryController;
use App\Http\Controllers\Admin\PortfolioController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\ServiceController;
use App\Http\Controllers\Admin\SliderController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\VideoGalleryController;
use App\Http\Controllers\Admin\WelcomenoteController;

// use GuzzleHttp\Middleware;



// Route::get('/', function () {
//     return view('welcome');
// });
// optimiZe
Route::get('/optimize', function() {
    $exitCode = Artisan::call('optimize');
    return 'DONE'; //Return anything
});

// admin route
// admin route
Route::get('/login',[AuthController::class, 'loginShow'])->name('login');
Route::post('/login',[AuthController::class, 'authCheck'])->name('login.check');

Route::group(['middleware' => ['auth']] , function(){
    Route::get('logout', [AuthController::class, 'logout'])->name('logout');
    Route::get('/',function(){
        return view('admin.index');
    })->name('dashboard');

    // admin all route here
    Route::prefix('setting')->group(function(){
             // Admin Register
            Route::get('/user-edit', [UserController::class, 'edit'])->name('user.edit');
            Route::put('/user-update', [UserController::class, 'updateUser'])->name('user.update');
            Route::get('/password/change', [UserController::class, 'passwordChange'])->name('password.change');
            Route::post('/password/update', [UserController::class, 'passwordUpdate'])->name('password.update');
    });

    //welcome note route
    Route::get('/welcome-note',[WelcomenoteController::class,'edit'])->name('welcome-note.edit');
    Route::put('/welcome-note/update',[WelcomenoteController::class,'update'])->name('welcome-note.update');

    //slider  route
    Route::resource('/slider',SliderController::class)->except('show','create');

    //service  route
    Route::resource('/service',ServiceController::class)->except('show','create');

   
    Route::prefix('product')->group(function(){
         //category  route
        Route::resource('/category',CategoryController::class)->except('show','create');
        //product  route
        Route::resource('/product',ProductController::class)->except('show');
    });
    

    //clident  route
    Route::resource('/client',ClientController::class)->except('show','create');

    //photo-gallery  route
    Route::resource('/photo-gallery',PhotoGalleryController::class)->except('show','create');

    //video-gallery  route
    Route::resource('/video-gallery',VideoGalleryController::class)->except('show','create');

      //Contact us  route
    Route::get('/contact-us',[ContactUsController::class,'index'])->name('contact.us');
    Route::post('/contact-us/update',[ContactUsController::class,'update'])->name('contact-us.update');
   
    //Content  route
    Route::get('content',[ContentController::class,'edit'])->name('content');
    Route::post('content-update',[ContentController::class,'update'])->name('content.update');
    Route::get('content-active',[ContentController::class,'active'])->name('content.active');

    //Portfolio  route
    Route::get('profile',[ProfileController::class,'edit'])->name('profile');
    Route::post('profile-update',[ProfileController::class,'update'])->name('profile.update');

     //message  route
     Route::get('message',[MessageController::class,'index'])->name('message');
     Route::delete('message-delete/{id}',[MessageController::class,'destroy'])->name('message.delete');

});

   

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    use HasFactory;
    protected $guarded = ['id'];
}

app/Http/Controllers/Admin/ClientController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Client;
use Illuminate\Http\Request;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = Client::latest()->get();
        return view('admin.client.index',compact('clients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->all());
        $this->validate($request, [
            'name' => 'required|max:200',
            'image' => 'required|max:10000||Image|mimes:jpg,png,jpeg,bmp',
          ]);

          $slider = new Client();
          $slider->name = $request->name;
          $slider->image = $this->imageUpload($request, 'image', 'uploads/client');
          $slider->save();

          if($slider){
            return back()->with('success','Slider Added Successfully');
          }
          else{
            return back()->with('error','Slider Added Fail!');
          }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Client $client)
    {
        return view('admin.client.edit',compact('client'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // dd($request->all());
        $request->validate([
            'name'=> 'max:255',
            'image' => 'max:1000||Image|mimes:jpg,png,jpeg,bmp',
        ]);

        $client = Client::first();
        $clientImage = '';
        if ($request->hasFile('image')) {
            if (file_exists($client->image)) {
                 unlink($client->image);
            }
            $clientImage = $this->imageUpload($request, 'image', 'uploads/client');
        } else {
            $clientImage = $client->image;
        }

        $client->name = $request->name;
        $client->image = $clientImage;
        $client->save();

        return redirect()->route('client.index')->with('success','Client Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $client = Client::where('id', $id)->first();
        if ($client->image) {
            @unlink($client->image);
        }
        $client->delete();
        return back()->with('success','Client Deleted Successfully');
    }
}

resources/views/admin/client/edit.blade.php
@extends('layouts.admin')
@section('title', 'Slider Add')
@section('admin-content')
    <main>
        <div class="container ">
            <div class="heading-title p-2 my-2 d-flex">
                <span class=" heading "><i class="fas fa-home"></i> <a class=""
                        href="{{ route('dashboard') }}">Home</a> >Slider</span>
                <span class=" heading ms-auto"><a class="" href="{{ route('client.index') }}">Back</a>
                    >Slider</span>

            </div>
            <form action="{{ route('client.update', $client->id) }}" method="post" enctype="multipart/form-data">
                @csrf
                @method('put')
                <div class="row justify-content-center">
                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-header">
                                <div class=""><i class="fas fa-cogs me-1"></i>Update Client</div>
                            </div>
                            <div class="card-body table-card-body">
                                <div class="row">
                                    <div class="col-md-3">
                                        <label><strong>Title :</strong></label>
                                    </div>
                                    <div class="col-md-9">
                                        <input type="text" value="{{ $client->name }}" class="form-control my-form-control"
                                            name="name">
                                    </div>
                                    <div class="col-md-3">
                                        <label><strong>Image :</strong></label>
                                    </div>
                                    <div class="col-md-5 mt-2">
                                        <input type="file" class="form-control my-form-control" id="image" name="image"
                                            onchange="readURL(this);">
                                    </div>
                                    <div class="col-md-4 mt-2">
                                        <img class="form-controlo img-thumbnail" src="#" id="previewImage"
                                            style="height:100px;width:120px; background: #3f4a49;">
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12 text-center">
                                        <button type="submit" class="btn btn-primary btn-sm mt-3 float-right"
                                            value="Submit">Update</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </form>
        </div>
    </main>
@endsection
@push('admin-js')
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function(e) {
                    $('#previewImage')
                        .attr('src', e.target.result)
                        .width(100);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
        document.getElementById("previewImage").src = "/noimage.png";
    </script>
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function(e) {
                    $('#previewImage')
                        .attr('src', e.target.result)
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
        document.getElementById("previewImage").src = "{{ asset($client->image) }}";
    </script>
@endpush

resources/views/admin/client/index.blade.php
@extends('layouts.admin')
@section('title', 'Client Add')
@section('admin-content')
    <main>
        <div class="container ">
            <div class="heading-title p-2 my-2">
                <span class="my-3 heading "><i class="fas fa-home"></i> <a class=""
                        href="{{ route('dashboard') }}">Home</a> >Slider</span>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <form action="{{ route('client.store') }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="card">
                            <div class="card-header">
                                <div class=""><i class="fas fa-cogs me-1"></i>Add Client</div>
                            </div>
                            <div class="card-body table-card-body">
                                <div class="row">
                                    <div class="col-md-3">
                                        <label><strong>Name :</strong></label>
                                    </div>
                                    <div class="col-md-9">
                                        <input type="text" class="form-control my-form-control" name="name">
                                    </div>
                                    <div class="col-md-3">
                                        <label><strong>Image :</strong></label>
                                    </div>
                                    <div class="col-md-5 mt-2">
                                        <input type="file" class="form-control my-form-control" id="image" name="image"
                                            onchange="readURL(this);">
                                    </div>
                                    <div class="col-md-4 mt-2">
                                        <img class="form-controlo img-thumbnail" src="#" id="previewImage"
                                            style="height:100px;width:120px; background: #3f4a49;">
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12 text-center">
                                        <button type="submit" class="btn btn-primary mt-2 btn-sm mt-3 float-right"
                                            value="Submit">Submit</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>

                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header">
                            <div class="table-head"><i class="fas fa-table me-1"></i>Client List <a href=""
                                    class="float-right"><i class="fas fa-print"></i></a></div>
                        </div>
                        <div class="card-body table-card-body p-3">
                            <table id="datatablesSimple">
                                <thead class="text-center bg-light">
                                    <tr>
                                        <th>SL</th>
                                        <th>Name</th>
                                        <th>image</th>
                                        <th width="20%" class="text-center">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($clients as $key => $item)
                                        <tr>
                                            <td>{{ $key + 1 }}</td>
                                            <td>{{ $item->title }}</td>
                                            <td>
                                                <img src="{{ asset($item->image) }}" alt=""
                                                    style="height: 60px;width:60px;margin:0 auto">
                                            </td>
                                            <td class="text-center">

                                                <a href="{{ route('client.edit', $item->id) }}"
                                                    class="btn btn-edit btn-sm"><i class="fas fa-edit"></i></a>
                                                <button type="submit" class="btn btn-delete"
                                                    onclick="deleteUser({{ $item->id }})"><i
                                                        class="far fa-trash-alt"></i></button>
                                                <form id="delete-form-{{ $item->id }}"
                                                    action="{{ route('client.destroy', $item->id) }}" method="POST"
                                                    style="display: none;">
                                                    @csrf
                                                    @method('DELETE')
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </main>
@endsection
@push('admin-js')
    <script src="{{ asset('admin') }}/js/sweetalert2.all.js"></script>
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function(e) {
                    $('#previewImage')
                        .attr('src', e.target.result)
                        .width(100);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
        document.getElementById("previewImage").src = "/noimage.png";
    </script>

    <script>
        function deleteUser(id) {
            swal({
                title: 'Are you sure?',
                text: "You want to Delete this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!',
                cancelButtonText: 'No, cancel!',
                confirmButtonClass: 'btn btn-success',
                cancelButtonClass: 'btn btn-danger',
                buttonsStyling: false,
                reverseButtons: true
            }).then((result) => {
                if (result.value) {
                    event.preventDefault();
                    document.getElementById('delete-form-' + id).submit();
                } else if (
                    // Read more about handling dismissals
                    result.dismiss === swal.DismissReason.cancel
                ) {
                    swal(
                        'Cancelled',
                        'Your data is safe :)',
                        'error'
                    )
                }
            })
        }
    </script>
@endpush