routes/web.php
<?php

use GuzzleHttp\Middleware;
use Brian2694\Toastr\Toastr;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Artisan;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ClientController;
use App\Http\Controllers\Admin\ContactUsController;
use App\Http\Controllers\Admin\ContentController;
use App\Http\Controllers\Admin\MessageController;
use App\Http\Controllers\Admin\PhotoGalleryController;
use App\Http\Controllers\Admin\PortfolioController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\ServiceController;
use App\Http\Controllers\Admin\SliderController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\VideoGalleryController;
use App\Http\Controllers\Admin\WelcomenoteController;

// use GuzzleHttp\Middleware;



// Route::get('/', function () {
//     return view('welcome');
// });
// optimiZe
Route::get('/optimize', function() {
    $exitCode = Artisan::call('optimize');
    return 'DONE'; //Return anything
});

// admin route
// admin route
Route::get('/login',[AuthController::class, 'loginShow'])->name('login');
Route::post('/login',[AuthController::class, 'authCheck'])->name('login.check');

Route::group(['middleware' => ['auth']] , function(){
    Route::get('logout', [AuthController::class, 'logout'])->name('logout');
    Route::get('/',function(){
        return view('admin.index');
    })->name('dashboard');

    // admin all route here
    Route::prefix('setting')->group(function(){
             // Admin Register
            Route::get('/user-edit', [UserController::class, 'edit'])->name('user.edit');
            Route::put('/user-update', [UserController::class, 'updateUser'])->name('user.update');
            Route::get('/password/change', [UserController::class, 'passwordChange'])->name('password.change');
            Route::post('/password/update', [UserController::class, 'passwordUpdate'])->name('password.update');
    });

    //welcome note route
    Route::get('/welcome-note',[WelcomenoteController::class,'edit'])->name('welcome-note.edit');
    Route::put('/welcome-note/update',[WelcomenoteController::class,'update'])->name('welcome-note.update');

    //slider  route
    Route::resource('/slider',SliderController::class)->except('show','create');

    //service  route
    Route::resource('/service',ServiceController::class)->except('show','create');

   
    Route::prefix('product')->group(function(){
         //category  route
        Route::resource('/category',CategoryController::class)->except('show','create');
        //product  route
        Route::resource('/product',ProductController::class)->except('show');
    });
    

    //clident  route
    Route::resource('/client',ClientController::class)->except('show','create');

    //photo-gallery  route
    Route::resource('/photo-gallery',PhotoGalleryController::class)->except('show','create');

    //video-gallery  route
    Route::resource('/video-gallery',VideoGalleryController::class)->except('show','create');

      //Contact us  route
    Route::get('/contact-us',[ContactUsController::class,'index'])->name('contact.us');
    Route::post('/contact-us/update',[ContactUsController::class,'update'])->name('contact-us.update');
   
    //Content  route
    Route::get('content',[ContentController::class,'edit'])->name('content');
    Route::post('content-update',[ContentController::class,'update'])->name('content.update');
    Route::get('content-active',[ContentController::class,'active'])->name('content.active');

    //Portfolio  route
    Route::get('profile',[ProfileController::class,'edit'])->name('profile');
    Route::post('profile-update',[ProfileController::class,'update'])->name('profile.update');

     //message  route
     Route::get('message',[MessageController::class,'index'])->name('message');
     Route::delete('message-delete/{id}',[MessageController::class,'destroy'])->name('message.delete');

});

   

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    protected $guarded = ['id'];
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        $category = Category::all();
        $product = Product::latest()->get();
        return view('admin.product.index', compact('product','category'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function create()
    {

    }

    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->all());
        $request->validate([
            'name' => 'required|max:100',
            'category_id' => 'required',
            'price' => 'required|max:10|regex:/^\d+(\.\d{1,2})?$/',
            'image' => 'required|image|mimes:jpg,png,gif,bmp|max:500',
        ]);
        $product = new Product();
        $product->name = $request->name;
        $product->category_id = $request->category_id;
        $product->price = $request->price;
        $product->image = $this->imageUpload($request, 'image', 'uploads/product');
        $product->description = $request->description;
        $product->save_by = 1;
        $product->ip_address = $request->ip();
        $product->save();
        return back()->with('success','Product Added Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::all();
        $product = Product::where('id', $id)->first();
        return view('admin.product.edit', compact('product', 'category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|max:100',
            'category_id' => 'required',
            'price' => 'required|max:18',
            'image' => 'image|mimes:jpg,png,gif,bmp|max:500',
            'ip_address' => 'max:15',
            // 'code' => 'max:18|unique:products,id',
        ]);

            $product = Product::find($id);
            
           
                $product_image = '';
                $product = Product::where('id', $id)->first();
                if ($request->hasFile('image')) {
                    if (!empty($product->image) && file_exists($product->image)) {
                        unlink($product->image);
                    }
                    $product_image = $this->imageUpload($request, 'image', 'uploads/product');
                } else {
                    $product_image = $product->image;
                }

            $product->name = $request->name;
            $product->category_id = $request->category_id;
            $product->price = $request->price;
            $product->description = $request->description;
            $product->image = $product_image;
            $product->save_by = Auth::user()->id;
            $product->ip_address = $request->ip();
            $product->save();
            return redirect()->route('product.index')->with('success', 'Product updated successfully');
        
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::find($id);
        if ($product->image) {
            @unlink($product->image);
        }
        $product->delete();
        return back()->with('success','product deleted successfully');
        
    }
}

resources/views/admin/product/edit.blade.php
@extends('layouts.admin')
@section('title', 'Product Update')
@push('admin-css')

@endpush
@section('admin-content')
    <main>
        <div class="container">
            <div class="heading-title p-2 my-2">
                <span class="my-3 heading "><i class="fas fa-home"></i> <a class=""
                        href="{{ route('dashboard') }}">Home</a> >Product Update</span>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header py-1"><span style="font-size: 14px;
                            font-weight: 600;
                            color: #0e2c96;">Edit Product</span> </div>
                        <div class="card-body table-card-body my-table">
                            <form action="{{ route('product.update', $product->id) }}" method="post"
                                enctype="multipart/form-data">
                                @csrf
                                @method('put')
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="row">

                                            <div class="col-md-4">
                                                <strong><label>Name</label><span class="color-red">*</span> <span
                                                        class="my-label">:</span> </strong>
                                            </div>
                                            <div class="col-md-8">
                                                <input type="text" name="name" value="{{ $product->name }}"
                                                    placeholder="Product Name"
                                                    class="form-control my-form-control @error('name') is-invalid @enderror">
                                                @error('name')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                @enderror
                                            </div>

                                            <div class="col-md-4">
                                                <strong><label>Price</label><span class="color-red">*</span> <span
                                                        class="my-label">:</span> </strong>
                                            </div>

                                            <div class="col-md-8">
                                                <input type="text" name="price" value="{{ $product->price }}"
                                                    placeholder="Price"
                                                    class="form-control my-form-control @error('price') is-invalid @enderror">
                                                @error('price')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                @enderror
                                            </div>

                                            <div class="col-md-4">
                                                <strong><label>Description</label><span class="color-red">*</span>
                                                    <span class="my-label">:</span> </strong>
                                            </div>
                                            <div class="col-md-8 mt-1">

                                                <textarea name="description" class="form-control" id="description"
                                                    cols="30" rows="3">{{ $product->description }}</textarea>
                                                @error('description')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                @enderror
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="row">
                                            <div class="col-md-4">
                                                <strong><label>Category</label><span class="color-red">*</span> <span
                                                        class="my-label">:</span> </strong>
                                            </div>
                                            <div class="col-md-8">
                                                <div class="input-group input-group-sm">
                                                    <select name="category_id" id="category_id"
                                                        class="custom-select js-example-basic-multiple form-control my-select my-form-control @error('category_id') is-invalid @enderror"
                                                        data-live-search="true">
                                                        <option value="">Select Category</option>
                                                        @foreach ($category as $item)
                                                            <option value="{{ $item->id }}"
                                                                {{ $product->category_id == $item->id ? 'selected' : '' }}>
                                                                {{ $item->name }}</option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                                @error('category_id')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                @enderror
                                            </div>
                                            <div class="col-md-4">
                                                <strong><label>Image</label> <span class="my-label">:</span> </strong>
                                            </div>
                                            <div class="col-md-5 mt-1">
                                                <input name="image" type="file"
                                                    class="form-control form-control-sm @error('image') is-invalid @enderror"
                                                    id="image" type="file" onchange="readURL(this);">
                                                @error('image')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                @enderror
                                            </div>
                                            <div class="col-md-3 mt-1">
                                                <img class="form-controlo img-thumbnail" src="#" id="previewImage"
                                                    style="width: 100px;height: 80px; background: #3f4a49;">
                                            </div>

                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <button type="submit"
                                            class="btn btn-primary btn-sm float-right mt-2">Update</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                </div>
            </div>
        </div>


    @endsection
    @push('admin-js')

        <script src="{{ asset('admin/js/ckeditor.js') }}"></script>
        <script>
            ClassicEditor
                .create(document.querySelector('#description'))
                .catch(error => {
                    console.error(error);
                });
        </script>
        <script>
            function readURL(input) {
                if (input.files && input.files[0]) {
                    var reader = new FileReader();
                    reader.onload = function(e) {
                        $('#previewImage')
                            .attr('src', e.target.result)
                    };
                    reader.readAsDataURL(input.files[0]);
                }
            }
            document.getElementById("previewImage").src = "{{ asset($product->image) }}";
        </script>
    @endpush